# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages
RUN npm install

# Make the CLI script executable
RUN chmod +x bin/cli.js

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Define environment variables
ENV AXIOM_TOKEN=<your-axiom-token>
ENV AXIOM_ORG_ID=<your-axiom-org-id>

# Run the application
ENTRYPOINT ["node", "bin/cli.js"]